#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: ./buildNdeploy <ip>"
	exit 1
fi

./build

scp backend/target/ChumPi-Backend-*.jar admin@$1:ChumPi/
tar --exclude=node_modules -cf - frontend/ | \
	ssh admin@$1 "rm -rf ChumPi/frontend; tar -C ChumPi -xvf -"
